#!/usr/bin/env ruby

require 'pp'

source_file = ARGV.shift
org_unit_id = ARGV.shift
tracked_entity_type_id = ARGV.shift

unless source_file
  puts   <<~DOC
    Must provide name of source file.

    Usage:
      patient_import <source_file> <org_unit_id> <tracked_entity_type_id>
  DOC

  abort
end

require 'csv'
require 'json'

patients = CSV.parse(File.open(source_file))

now = DateTime.now.iso8601(3)

report_timestamp = patients.shift
human_headers = patients.shift
dhis2_headers = patients.shift

dhis2_patients = patients.map do |patient|
  patient_data = dhis2_headers.zip(patient).to_h
  patient_data.delete(nil)

  patient_attributes = patient_data.map do |attr_id, value|
    {
      attribute: attr_id,
      value: value
    }
  end

  {
    orgUnit: org_unit_id,
    createdAtClient: now,
    lastUpdated: now,
    trackedEntityType: tracked_entity_type_id,
    lastUpdatedAtClient: now,
    inactive: false,
    deleted: false,
    featureType: "NONE",
    programOwners: [],
    enrollments: [],
    relationships: [],
    attributes: patient_attributes
  }
end

puts({ trackedEntityInstances: dhis2_patients }.to_json)
